### ISSUE TITLE
03 - using docker - add sharing of local file systems

### ISSUE THREAD

**Issue by katilp** [cms-opendata-workshop/workshop-lesson-docker-preexercises#11]
Comment on https://cms-opendata-workshop.github.io/workshop-lesson-docker-preexercises/03-testing-docker-for-cms-opendata/index.html

In many cases, mounting a local directory is really handy, and instructions should be added for it as it may not be obvious from the /cvmfs mount example. Add a section "Passing files through mounted volumes" before or after Copying files

`docker run -v <path on host>:<path in container> <image>
`

**Comment by mattbellis** [comment]
OK. Done. I also have some minimal comments about mounting volumes at the beginning since we use these flags, but there's now a dedicated section where you suggested.
