### ISSUE TITLE
05 - test and validate - add mounted volume

### ISSUE THREAD

**Issue by katilp** [cms-opendata-workshop/workshop-lesson-docker-preexercises#12]
Comment on https://cms-opendata-workshop.github.io/workshop-lesson-docker-preexercises/05-validation/index.html

As in #11, it would be useful to mention mounted volumes after "IMPORTANT NOTE: Depending on your system, there could be some issues with the shared clipboard between the host machine and the Docker container.
This means that it is possible that you cannot copy the instrucitons in this episode directly into your Docker session."

It is really very practical to be able to edit directly on host and not needing to worry about available editors or copy-pasting on the container.

**Comment by mattbellis** [comment]
I'm not sure what would make sense here, given that the pre-exercise lessons are starting to expand. We mentioned mounted volumes in the 3rd part of this and when they run through the CVMFS module (prior to validation), they use brilcalc so they test the mounting procedure. 

Maybe you're suggesting the mount a local directory that has their code in there and they view it in the docker image? That would be useful but it might take a bit to put together something good. Let me know if this is what you mean and I'll put something together.

**Comment by mattbellis** [comment]
I'm also wondering if this potentially confuses the workflow? Or the other lessons?

**Comment by katilp** [comment]
Yes, I mean mounting the local directory. It certainly does not confuse workflow as if done -v $PWD:$PWD it will just make the container pwd available on local host and make it easier to edit there. I think, to get started, this is more important than for example the ssh directory passing.

**Comment by katilp** [comment]
That would be:

**On the local host** - create the container with a local directory mounted

```
mkdir testdir
cd testdir
docker run  -it --name mytest -v ${HOME}/testdir:/home/cmsusr:shared cmsopendata/cmssw_5_3_32 /bin/bash
```

**On the container**  - create the CMSSW area (happens automatically at the start), check and exit

```
pwd
exit
```
**On the local host** - get the code with git clone and go back to the same container

```
cd CMSSW_5_3_32/src/
mkdir workspace
cd workspace
git clone https://github.com/katilp/AOD2NanoAODOutreachTool.git AOD2NanoAOD
docker start -i mytest
```
**On the container**  - compile the code and run

```
cd workspace/AOD2NanoAOD/
scram b
cmsRun configs/data_cfg.py
```

Now the code and the output files are available both **on the local host** and **on the container**.
- Editing files can be done in both sides. 
- All git commands should be done **on the local host** 
- Compiling  and running must be done **on the container**.
- The resulting output.root can be analyzed wherever the appropriate version of root is made available, or passed similarly in a root container with a proper volume mounting.


The commands above with the output:
```
kati@LAPTOP-D2GA3D2E:~$ mkdir testdir
kati@LAPTOP-D2GA3D2E:~$ cd testdir
kati@LAPTOP-D2GA3D2E:~/testdir$ docker run  -it --name mytest -v ${HOME}/testdir:/home/cmsusr:shared cmsopendata/cmssw_5_3_32 /bin/bash
Setting up CMSSW_5_3_32
Waiting for release information to be obtained via https://cmssdt.cern.ch/SDT/releases.map (timeout in 7s)
CMSSW should now be available.
bash-4.1$ pwd
/home/cmsusr/CMSSW_5_3_32/src
bash-4.1$ exit
exit
kati@LAPTOP-D2GA3D2E:~/testdir$ cd CMSSW_5_3_32/src/
kati@LAPTOP-D2GA3D2E:~/testdir/CMSSW_5_3_32/src$ mkdir workspace
kati@LAPTOP-D2GA3D2E:~/testdir/CMSSW_5_3_32/src$ cd workspace
kati@LAPTOP-D2GA3D2E:~/testdir/CMSSW_5_3_32/src/workspace$ git clone https://github.com/katilp/AOD2NanoAODOutreachTool.git AOD2NanoAOD
Cloning into 'AOD2NanoAOD'...
remote: Enumerating objects: 57, done.
remote: Counting objects: 100% (57/57), done.
remote: Compressing objects: 100% (52/52), done.
remote: Total 340 (delta 28), reused 10 (delta 4), pack-reused 283
Receiving objects: 100% (340/340), 741.92 KiB | 650.00 KiB/s, done.
Resolving deltas: 100% (161/161), done.
kati@LAPTOP-D2GA3D2E:~/testdir/CMSSW_5_3_32/src/workspace$ cd AOD2NanoAOD/
kati@LAPTOP-D2GA3D2E:~/testdir/CMSSW_5_3_32/src/workspace/AOD2NanoAOD$ docker start -i mytest
Setting up CMSSW_5_3_32
WARNING: There already exists /home/cmsusr/CMSSW_5_3_32 area for SCRAM_ARCH slc6_amd64_gcc472.
CMSSW should now be available.
bash-4.1$ pwd
/home/cmsusr/CMSSW_5_3_32/src
bash-4.1$ cd workspace/AOD2NanoAOD/
bash-4.1$ scram b
>> Local Products Rules ..... started
>> Local Products Rules ..... done
>> Entering Package workspace/AOD2NanoAOD
>> Creating project symlinks
  src/workspace/AOD2NanoAOD/python -> python/workspace/AOD2NanoAOD
Entering library rule at workspace/AOD2NanoAOD
>> Compiling edm plugin /home/cmsusr/CMSSW_5_3_32/src/workspace/AOD2NanoAOD/src/AOD2NanoAOD.cc
>> Building edm plugin tmp/slc6_amd64_gcc472/src/workspace/AOD2NanoAOD/src/workspaceAOD2NanoAOD/libworkspaceAOD2NanoAOD.so
Leaving library rule at workspace/AOD2NanoAOD
@@@@ Running edmWriteConfigs for workspaceAOD2NanoAOD
--- Registered EDM Plugin: workspaceAOD2NanoAOD
>> Leaving Package workspace/AOD2NanoAOD
>> Package workspace/AOD2NanoAOD built
>> Local Products Rules ..... started
>> Local Products Rules ..... done
gmake[1]: Entering directory `/home/cmsusr/CMSSW_5_3_32'
>> Creating project symlinks
  src/workspace/AOD2NanoAOD/python -> python/workspace/AOD2NanoAOD
>> Done python_symlink
>> Compiling python modules python
>> Compiling python modules src/workspace/AOD2NanoAOD/python
>> All python modules compiled
@@@@ Refreshing Plugins:edmPluginRefresh
>> Pluging of all type refreshed.
>> Done generating edm plugin poisoned information
gmake[1]: Leaving directory `/home/cmsusr/CMSSW_5_3_32'
bash-4.1$ cmsRun configs/data_cfg.py
200924 10:15:31 782 Xrd: XrdClientConn: Error resolving this host's domain name.
200924 10:15:31 782 secgsi_InitProxy: cannot access private key file: /home/cmsusr/.globus/userkey.pem
24-Sep-2020 10:23:46 CEST  Initiating request to open file root://eospublic.cern.ch//eos/opendata/cms/Run2012B/TauPlusX/AOD/22Jan2013-v1/20000/0040CF04-8E74-E211-AD0C-00266CFFA344.root
24-Sep-2020 10:23:49 CEST  Successfully opened file root://eospublic.cern.ch//eos/opendata/cms/Run2012B/TauPlusX/AOD/22Jan2013-v1/20000/0040CF04-8E74-E211-AD0C-00266CFFA344.root
24-Sep-2020 10:27:54 CEST  Closed file root://eospublic.cern.ch//eos/opendata/cms/Run2012B/TauPlusX/AOD/22Jan2013-v1/20000/0040CF04-8E74-E211-AD0C-00266CFFA344.root

=============================================

MessageLogger Summary

 type     category        sev    module        subroutine        count    total
 ---- -------------------- -- ---------------- ----------------  -----    -----
    1 fileAction           -s file_close                             1        1
    2 fileAction           -s file_open                              2        2

 type    category    Examples: run/evt        run/evt          run/evt
 ---- -------------------- ---------------- ---------------- ----------------
    1 fileAction           PostEndRun
    2 fileAction           pre-events       pre-events

Severity    # Occurrences   Total Occurrences
--------    -------------   -----------------
System                  3                   3
bash-4.1$ ls -l *root
-rw-r--r-- 1 cmsusr cmsusr 56058 Sep 24 10:27 output.root
bash-4.1$ exit
exit
kati@LAPTOP-D2GA3D2E:~/testdir/CMSSW_5_3_32/src/workspace/AOD2NanoAOD$ ls -l *root
-rw-r--r-- 1 kati kati 56058 Sep 24 11:27 output.root
```

**Comment by katilp** [comment]
@mattbellis @caredg Would you like me to add this (i.e. the commands - not the ouput) in the pink box with IMPORTANT NOTE
in https://cms-opendata-workshop.github.io/workshop-lesson-docker-preexercises/05-validation/index.html ?
I think the exact order of commands would be helpful to have, in particular, in case of problems. I can do it now.

**Comment by caredg** [comment]
@katilp I am fine with it.  That is certainly very practical.  I always mount a `playground` local host area in my docker.  Since I am an xemacs guy, it helps for heavy editing...

**Comment by katilp** [comment]
OK, I'll add (and remove the video link which is for VM and not for docker).

**Comment by katilp** [comment]
Nope, finally, it does not fit well here. This episode is with the basic demoanalyzer and it would be confusing to add an example accessing a git cloned repo here. I'll see if there's another place for it.

**Comment by caredg** [comment]
Actually, now that I see this in more detail, it could be really confusing.  Wouldn't it be better to suggest [here](https://github.com/cms-opendata-workshop/workshop-lesson-docker-preexercises/blame/gh-pages/_episodes/03-testing-docker-for-cms-opendata.md#L54) to mount an area from the host, call it `bufferzone`, so they can copy files there if they need to be edited on the host and copy them back to the original area in the container? Or actually [here](https://github.com/cms-opendata-workshop/workshop-lesson-docker-preexercises/blame/gh-pages/_episodes/03-testing-docker-for-cms-opendata.md#L256).  We could just stress the fact that it could be much easier to deal with some file editing using the buffer zone.

**Comment by katilp** [comment]
Note that this not only for editing but also for using git (for easier push without the need of any tricks for the old protocol on the OD container).
In order not to mess it up (at least for a git dummy like me), it is easiest git clone in a local host directory without copying. I.e. one gets a proper git area with all settings for push on the local host and at the same time, the code is ready to be compiled on the the container.

**Comment by katilp** [comment]
But we can see if this becomes an issue and come back to this during the workshop.

**Comment by caredg** [comment]
I see. I am really afraid of asking them to push to git repositories though.  It is nice that they could save their work there, but it seems that that would add a lot of complications.  Gitting is not so not intuitive at the beginning....  Right, let see how it goes...

**Comment by mattbellis** [comment]
OK, I think I see now how this workflow goes. Sorry about my reticence. I just didn't grok this. 

Making a bunch of changes now. Should push in < 1 hour.

**Comment by mattbellis** [comment]
@katilp Your first few commands fail for me. 

```
(base) bellis@titan:~$ mkdir testdir
(base) bellis@titan:~$ cd testdir/
(base) bellis@titan:~/testdir$ docker run  -it --name mytest -v ${HOME}/testdir:/home/cmsusr:shared cmsopendata/cmssw_5_3_32 /bin/bash
Setting up CMSSW_5_3_32
cannot make directory CMSSW_5_3_32 Permission denied
```

**Comment by mattbellis** [comment]
However, this works for me if I specify the mount point in the image. 

```
(base) bellis@titan:~/testdir$ docker run  -it --name mytest -v ${HOME}/testdir:/home/cmsusr/testdir:shared cmsopendata/cmssw_5_3_32 /bin/bash
Setting up CMSSW_5_3_32
CMSSW should now be available.
```

**Comment by mattbellis** [comment]
@katilp Do you have CMSSW_5_3_32 installed on your laptop? Is that why this is working? I don't have that.

I'm going to put together an alternative approach that I think will work. Will post soon.

**Comment by mattbellis** [comment]
OK, I think there's information in there for mounting a local volume which will work. 

I removed all references to .ssh keys and checking out things with git inside the docker container. 

I have the code working with @katilp 's example to the point of checking out the code, but not running it.

**Comment by mattbellis** [comment]
And now I'm finding that the way I ran it, by using a soft link doesn't work. 

```
[21:06:35] cmsusr@titan ~/CMSSW_5_3_32/src/cms_open_data_work/AOD2NanoAOD $ scram b
SCRAM fatal: Unable to locate the top of local release. Please run this command from a SCRAM-based area.
```

So I'm not sure what to do. @katilp 's command doesn't work for me and what I tried doesn't work either.

**Comment by mattbellis** [comment]
Nope! Never mind! Ran scram from the wrong directory. :D

**Comment by mattbellis** [comment]
OK, I think I got it working, but on my machine, there are issues with how the volumes are getting mounted in the Docker container. They're all getting mounted as `cmsinst` for both the user and group. So builds are failing. I'll add some additional commands to make sure that's not an issue.

**Comment by mattbellis** [comment]
Trying to run the `cmsRun...` part, but it seems to take a long time.

**Comment by katilp** [comment]
@mattbellis got a bit lost in the thread 😃 So does the initial `-v ${HOME}/testdir:/home/cmsusr:shared` work for you?
I do not have any CMSSW initially mounted, the `testdir` directory is newly created and empty. It is creating the container instance with `docker run...` that actually created the CMSSW area and as it a shared area it would be available on both sides.


For the cmsRun part, it clones from my area in the instructions above (as it is meant to show how get a github area where one can actully push back for saving ones own work). It may be that n events is high there, I'll check. Do not add cloning from there to instructions.

However, as this get complicated just leave it as it is. As I mentioned above, I do not think it fits to this page in any case, because this page stays in mkedanlzr level and we are not yet at cloning any examples.

**Comment by mattbellis** [comment]
Yeah, sorry about that. I shouldn't stream-of-consciousness reply to Issues.  :)

The initial `-v ${HOME}/testdir:/home/cmsusr:shared` does not work. I get the 

```
cannot make directory CMSSW_5_3_32 Permission denied
```

**Comment by mattbellis** [comment]
Quick question, when you ran the AOD2NanoAOD config with `cmsRun`, how long did it take? The way I've set things up, I can `scram` but the `cmsRun` command has been sitting there for 10 min and isn't doing anything. Nor is it just crashing and returning a prompt.

**Comment by katilp** [comment]
And you've created an empty  `testdir` on local host first?

We've seen that elsewhere (i.e. mounted volumes being created under `cmsint` and not under `cmsusr` ), so it may indeed be due to some docker (or other) settings. We've just seen that with the docker-in-browser setup with @clelange . 

Do not then add those instructions, for once that's something that works on my setup, but not necessarily elsewhere (usually it is the other way round 😉 )

**Comment by katilp** [comment]
From the output I can see that it took 8 mins from the first message to opening the file.

**Comment by mattbellis** [comment]
@katilp Yeah, I created the `testdir` locally first. 

OK, yeah something's hanging on mine if it's taking 8 min. However, even without this local volume tesdir issue, on another "normal" instance, when I check out and scram the AOD2nano stuff, it's still hanging. 

I'll play with this a bit more later tonight but I'll be away from the computer for a few hours now. I'll keep on this! We can then decide if we want these instructions or not. 

If it works, it's the best way to handle things! Users need a workflow that allows them to use version control on their scripts as they are developing them.

**Comment by mattbellis** [comment]
OK, I've got something that I think works. We'll see! :)

**Comment by katilp** [comment]
@mattbellis I think you cloned from my fork in the example. It should work without problems but that's not ideal as it may cause confusion later on. 
Would you change it to https://github.com/cms-opendata-analyses/AOD2NanoAODOutreachTool ?
Or maybe you left it on purpose as my fork has a small number of events, while the original one has -1 so my config file does not require changes.
(a real use-case would be to fork an area of one's own and clone from there, but maybe no need for that at this point)

**Comment by mattbellis** [comment]
@katilp Ha! I didn't even quite catch that I was cloning your own fork.  :+1: 

If yours has a smaller number of events, let's use yours. I'm finding it's taking 20-30 min on my machine but maybe that's just connection issues from the US? I wonder what the order is for the code. I noticed that it's looking in the text files for all those different files and file locations. If it has to check them all *before* it decides to run over 100 events, I wonder if that's the bottleneck?
