### ISSUE TITLE
cvmfs installation on the container

### ISSUE THREAD

**Issue by caredg** [cms-opendata-workshop/workshop-lesson-docker-preexercises#13]
@mattbellis in order to address [Kevin's suggestion](https://mattermost.web.cern.ch/cmsopendatatheo/pl/p3c3jzcrwtd1mjbeu7nqea85yc) on mattermost, which is valid, and since I do not know if someone who knows how to build docker images properly will be available, I tested these instructions on my machine for installing `cvmfs` directly on the container and they worked beautifully for me (hopefully for others).  I don't know if they can be added to the instructions, but at least it would be good to have them at hand in case they are useful:

These instructions are based on the official documentation [here](https://cvmfs.readthedocs.io/en/stable/cpt-quickstart.html) and [here](https://cvmfs.readthedocs.io/en/stable/cpt-configure.html).

Create the container on the host with the `--privileged` option with something like this:
```bash
docker run --privileged --name od2011cvmfs -it --net=host --env="DISPLAY" --volume="$HOME/.Xauthority:/root/.Xauthority:rw" --volume="/home/ecarrera/.ssh:/home/cmsusr/.ssh" -v "/home/ecarrera/playground:/playground" cmsopendata/cmssw_5_3_32 /bin/bash
```

The rest of the commands will be executed on the container.

Install the cvmfs client
```
sudo yum install https://ecsft.cern.ch/dist/cvmfs/cvmfs-release/cvmfs-release-latest.noarch.rpm
sudo yum install -y cvmfs
```

Configure autofs
```
sudo cvmfs_config setup
```

Create the /etc/cvmfs/default.local file
```
sudo vi /etc/cvmfs/default.local
```
by adding these lines:
> CVMFS_REPOSITORIES='cms-opendata-conddb.cern.ch'
CVMFS_HTTP_PROXY=DIRECT

Restart autofs
```
sudo service autofs restart
```

Verify the file system
```
cvmfs_config probe
```
(repeat the last two commands every time you restart the container)

**Comment by katilp** [comment]
Works perfectly fine on docker from WSL2 Ubuntu.

For the record, one could already add in the instructions `bril` with

```
CVMFS_REPOSITORIES=cms.cern.ch,cms-opendata-conddb.cern.ch,cms-bril.cern.ch
CVMFS_HTTP_PROXY=DIRECT
CVMFS_CLIENT_PROFILE=single
```
which works as well.

**Comment by mattbellis** [comment]
@caredg OK, let me add this now!

**Comment by mattbellis** [comment]
OK, I'm still going through the commands but I'm assuming the work. These instructions are added!
