### ISSUE TITLE
03 - add the exact command for the soft link

### ISSUE THREAD

**Issue by katilp** [cms-opendata-workshop/workshop-lesson-docker-preexercises#14]
In https://cms-opendata-workshop.github.io/workshop-lesson-docker-preexercises/03-testing-docker-for-cms-opendata/index.html

Great that this works, thanks for figuring that out 💪 ! In "The easiest thing to do is to create a soft link to that directory from inside /home/cmsusr/CMSSW_5_3_32/src and then do your work in there", please add the exact command to create the soft link.

**Comment by mattbellis** [comment]
I did have that a few lines down, but I see it's not obvious. 

I've added some text to clarify this.

**Comment by katilp** [comment]
Oh I'm sorry I didn't see that. Maybe best to add it immediately (for other inpatient readers like me ;-) )

**Comment by katilp** [comment]
Sorry for being a real trouble 🙂 : please add the full command (or add "as shown below" after `...`) . If people are unfamiliar with soft links they would not know how to complete it, and uncomplete commands are frustrating 😉

**Comment by mattbellis** [comment]
Done! Added "as shown below".
