### ISSUE TITLE
03 & 05: use of soft link with mkedanalzr fails

### ISSUE THREAD

**Issue by katilp** [cms-opendata-workshop/workshop-lesson-docker-preexercises#15]
Just for record: in the docker play environment http://docker.cms-cloud.ml/ from @clelange   (which for the volume mounts and permission seems to behave like that of @mattbellis ), if the container mounts a local volume as instructed under "Mounting a local volume" in
https://cms-opendata-workshop.github.io/workshop-lesson-docker-preexercises/03-testing-docker-for-cms-opendata/index.html

then `mkedanlzr` (done in https://cms-opendata-workshop.github.io/workshop-lesson-docker-preexercises/05-validation/index.html fails)

```
root@node1:~# mkdir test
root@node1:~# docker run -it --name myopendataproject -v ${HOME}/test:/home/cmsusr/test cmsopendata/cmssw_5_3_32 /bin/bashUnable to find image 'cmsopendata/cmssw_5_3_32:latest' locally
latest: Pulling from cmsopendata/cmssw_5_3_32
e8114d4b0d10: Pull complete 
a3eda0944a81: Pull complete 
a88502447863: Pull complete 
Digest: sha256:6b9a12992ba088a168b87df98a841d3c56dede326684f5551368fd359acfb43c
Status: Downloaded newer image for cmsopendata/cmssw_5_3_32:latest
Setting up CMSSW_5_3_32
CMSSW should now be available.
[08:55:35] cmsusr@fd6b975e3b22 ~/CMSSW_5_3_32/src $ sudo chown -R cmsusr.cmsusr ~/test
[08:56:03] cmsusr@fd6b975e3b22 ~/CMSSW_5_3_32/src $ ln -s ~/test/
[08:56:46] cmsusr@fd6b975e3b22 ~/CMSSW_5_3_32/src $ ls
test
[08:56:48] cmsusr@fd6b975e3b22 ~/CMSSW_5_3_32/src $ cd test
[08:56:52] cmsusr@fd6b975e3b22 ~/CMSSW_5_3_32/src/test $ mkedanlzr DemoAnalyzer
Packages must be created in a 'subsystem'.
  Please go to '$CMSSW_BASE/src', create or choose a subdirectory from there
  and then run the script from that subdirectory.
[09:00:58] cmsusr@fd6b975e3b22 ~/CMSSW_5_3_32/src/test $ 

```

Doing it in a normal subdirectory (not a soft link) works

```
[09:00:58] cmsusr@fd6b975e3b22 ~/CMSSW_5_3_32/src/test $ cd ..
[09:10:29] cmsusr@fd6b975e3b22 ~/CMSSW_5_3_32/src $ mkdir Demo
[09:10:50] cmsusr@fd6b975e3b22 ~/CMSSW_5_3_32/src $ cd Demo/
[09:10:55] cmsusr@fd6b975e3b22 ~/CMSSW_5_3_32/src/Demo $ mkedanlzr DemoAnalyzer
  I: using skeleton: /opt/cms/slc6_amd64_gcc472/cms/cmssw/CMSSW_5_3_32/bin/slc6_amd64_gcc472/mkTemplates/EDAnalyzer/ConfFile_cfg.py 
  I: authors name is: , determined by the gcos entry 
  I: creating file:  DemoAnalyzer/demoanalyzer_cfg.py 
....
```

**Comment by clelange** [comment]
I think we should teach using [volumes](https://docs.docker.com/engine/reference/commandline/volume/) instead of simply mounting directories from the host system.

With docker-in-docker, things are a bit more special (from https://stackoverflow.com/questions/31381322/docker-in-docker-cannot-mount-volume, it also mentions soft-links):

> A Docker container in a Docker container uses the parent HOST's Docker daemon and hence, any volumes that are mounted in the "docker-in-docker" case is still referenced from the HOST, and not from the Container.
> Therefore, the actual path mounted from the CMS container "does not exist" in the HOST. Due to this, a new directory is created in the "docker-in-docker" container that is empty. Same thing applies when a directory is mounted to a new Docker container inside a Container. 

I'll check later if there's a somewhat fail-safe approach.

**Comment by katilp** [comment]
Right, but we probably need to distinguish the use-cases
1. those getting started: who just need to get editing or looking at the output files working
2. those getting to real work: ⬆️ for whom the solutions can be more involved

and make sure that the solutions for 2 are not confusing the people in 1.

**Comment by caredg** [comment]
not using this for this workshop, I suppose. closing
