### ISSUE TITLE
Installing CVMFS directly in the Docker container

### ISSUE THREAD

**Issue by clelange** [cms-opendata-workshop/workshop-lesson-docker-preexercises#16]
In "Install CVMFS directly in the Docker container" of https://cms-opendata-workshop.github.io/workshop-lesson-docker-preexercises/04-cvmfs-and-brilcalc/index.html

There were issues with installing CVMFS into the container on Mac. The general solution (should also work on non-Mac systems is as follows):

This is from beginning to end (starting outside the container), but if already inside start further below.

```
cd
mkdir cms_open_data_work
docker run --privileged -it --name myopendataproject --net=host --env="DISPLAY" --volume="$HOME/.Xauthority:/home/cmsusr/.Xauthority:rw" -v ${HOME}/cms_open_data_work:/home/cmsusr/cms_open_data_work cmsopendata/cmssw_5_3_32 /bin/bash
```

Then we're in the docker container:

```
sudo yum install -y https://ecsft.cern.ch/dist/cvmfs/cvmfs-release/cvmfs-release-latest.noarch.rpm
sudo yum install -y cvmfs
sudo vi /etc/cvmfs/default.local
```

Add these lines:

```
CVMFS_REPOSITORIES=cms.cern.ch,cms-opendata-conddb.cern.ch,cms-bril.cern.ch
CVMFS_HTTP_PROXY=DIRECT
CVMFS_CLIENT_PROFILE=single
```

Then back to the shell in the container:

```
sudo chgrp fuse /dev/fuse
sudo vi /etc/fstab
```

Add these lines:

```
cms.cern.ch /cvmfs/cms.cern.ch cvmfs defaults 0 0
cms-opendata-conddb.cern.ch /cvmfs/cms-opendata-conddb.cern.ch cvmfs defaults 0 0
cms-bril.cern.ch /cvmfs/cms-bril.cern.ch cvmfs defaults 0 0
```

Then back to the shell in the container:

```
sudo mkdir -p  /cvmfs/cms.cern.ch
sudo mkdir -p  /cvmfs/cms-opendata-conddb.cern.ch 
sudo mkdir -p  /cvmfs/cms-bril.cern.ch
sudo cvmfs_config setup
sudo mount -a
```

This should then mount CVMFS....

**Comment by caredg** [comment]
not using this for the next version of the workshop.  Closing
