### ISSUE TITLE
Check :shared options

### ISSUE THREAD

**Issue by mattbellis** [cms-opendata-workshop/workshop-lesson-docker-preexercises#17]
Some of the docker mount commands have the `shared` option, but this created an issue for one users MacOS Catalina. 

@clelange Suggests we don't need this. We should check out the command *without* the shared option and remove it from the documentation if it is not necessary.

**Comment by clelange** [comment]
We should test this on Linux. These flags are additional qualifiers, which, however, do not persist across different host systems

**Comment by caredg** [comment]
addressed, I do not think we use this any longer....closing
