### ISSUE TITLE
04: increase cvmfs quota

### ISSUE THREAD

**Issue by katilp** [cms-opendata-workshop/workshop-lesson-docker-preexercises#18]
In some cases, the default 4G limit for the cvmfs is not enough. That quota can be checked with `df`.

If the downloaded condition data are more than that, the system starts autodeletion and this is not optimal for timing. The deleted parts need to be cached again when needed.
NB this is a feature of  the sqlite download, it downloads everything even if only small part is needed, in this case the jec files.

This can be solved by an additional setting in `/etc/cvmfs/default.local`:

`CVMFS_QUOTA_LIMIT=8000`

This should be added to the instructions.

**Comment by caredg** [comment]
Maybe not relevant to newer version of workshop as we are not reaching through cvmfs
