### ISSUE TITLE
From the mattermost chat: short comments

### ISSUE THREAD

**Issue by katilp** [cms-opendata-workshop/workshop-lesson-docker-preexercises#19]
Short comments from [the mattermost chat](https://mattermost.web.cern.ch/cmsopendatatheo/channels/docker-pre-exercises)

- [x] clarify in `docker run -v <path on host>:<path in container> <image>` what does image stand for e.g. `cmsopendata/cmssw_5_3_32`

- [x] deleting unwanted containers:  On the host you can do `docker ps -a` to list all of them and then `docker container rm <nameOfUnwantedContainer>` to delete it.  The image, as you can see with `docker image ls`, will still be there, so you can play with it as much as you like.

- [ ] clarify that the volumes should be mounted  (or its is easiest to mount them) to the container right at the start, i.e. ath firts `docker run ...`

- [x]  The only editor is "vi", so how can one install a preferred text editor? With 	`sudo yum install nano`

- [ ] clarify, when talking about Windows and WSL, that "on local host" one should use the linux instructions and run them on the Windows WSL local linux installation 

- [ ] for an error an error stating:
"docker: Error response from daemon: path /Users/philipp/PhD/cms_open_data_workshop is mounted on /Users but it is not a shared mount.". Remove `:shared`

- [ ] `pip install --user brilws` may take time

**Comment by caredg** [comment]
I am closing this here, but it has been referenced

**Comment by caredg** [comment]
I am closing this here, but it has been referenced
