### ISSUE TITLE
Few things

### ISSUE THREAD

**Issue by caredg** [cms-opendata-workshop/workshop-lesson-docker-preexercises#2]
Hi @mattbellis, thanks! I have not gone through every step (it is a bit late).  I am sure @Mmintyyy (Kati's student) can test them out.... but just a few things:
- I switched to gh-pages as the the default branch.
- change to at least alpha in the _config.yml file
- the [setup](https://cms-opendata-workshop.github.io/workshop-lesson-docker-preexercises/setup.html) page has a FIXME there, as well as the [Glossary](https://cms-opendata-workshop.github.io/workshop-lesson-docker-preexercises/reference.html#glossary), etc.  Maybe we can just delete those FIXME tags that are lingering around.
- The [improve this page](https://github.com/cms-opendata-workshop/workshop-lesson-docker-preexercises/edit/master/LICENSE.md) points to the master, I do not know why.  Maybe we can just leave it...
- Actually we need access to cvmfs not only for the luminosity exercise but also for the trigger (an perhaps for testing the ntuplizer).  It is actually possible to install cvmfs in the docker container (perhaps we should not go that route though)
Thanks and get some sleep!

**Comment by caredg** [comment]
Oh, and for the logo, take a look a [this](https://github.com/cms-opendata-workshop/workshop-lesson-virtualmachine/blame/gh-pages/_episodes/03-cmsvmimage.md#L41) similar line for a locally stored file. It is much simpler to reference it that way.

**Comment by mattbellis** [comment]
* Now is alpha
* Setup now has the prereqs from the opening page. FIXME removed from Glossary
* Maybe the gh-pages switch will propagate soon?
* Language added in the CVMFS section to reference the trigger tools. I did see the instructions to install CVMFS in docker, but I figured I'd pick one and run with it. I think it makes it more robust for the user anyways, but maybe that's just me.

**Comment by mattbellis** [comment]
Also, you're right! That *is* a much easier way to reference local files! :)
