### ISSUE TITLE
Episode 3: start and attach gives error

### ISSUE THREAD

**Issue by nooraangelva** [cms-opendata-workshop/workshop-lesson-docker-preexercises#21]
In episode 3 : [_episodes/03-testing-docker-for-cms-opendata.md](url)
chapter: Start/Attach to a particular process [https://github.com/cms-opendata-workshop/workshop-lesson-docker-preexercises/blob/gh-pages/_episodes/03-testing-docker-for-cms-opendata.md#startattach-to-a-particular-process](url)

the codes bellow give an error often (_you cannot attach to a stopped container_ )
```
docker start 7719a7d74190
docker attach 7719a7d74190
```

I found a solution to this in the bellow link and used the following command: 
`docker start -a "containerID"`

[https://docs.docker.com/engine/reference/commandline/start/](url)

**Comment by mattbellis** [comment]
Ah, nice! So does the `-a` just mean that it won't try starting it if an instance with that ID is not running?

**Comment by nooraangelva** [comment]
`-a` means it will attach the container id when it is started. so the code that I found merges the two lines of code that gave an error.

**Comment by mattbellis** [comment]
Excellent! I've made the edit and pushed the changed!

**Comment by mattbellis** [comment]
changed --> changes. :)
