### ISSUE TITLE
Comments from testing

### ISSUE THREAD

**Issue by Mmintyyy** [cms-opendata-workshop/workshop-lesson-docker-preexercises#3]
### Setup
- In the instructions it says that you need "2-4 GB of free memory". Are we talking about RAM or hard drive storage here? As a Windows user, I think I needed like 10 GB of free hard drive space (did not have Docker or Ubuntu installed before). This could be useful for the user to know, as at least for me it took a while to clean up my files and programs to get some space.

### Installing Docker
- I needed to install a Windows 10 update, before I was able to download Docker and free up a lot of space on my computer to do that, which took a while. It is good to notice that some participants might need to do this as well.
- On the Docker Hub page, I was unsure whether to install Stable or Edge version (after some googling decided to go with Stable, but this could already be included in the instructions)
- Overall, I found the Docker for Windows download instructions a bit overwhelming, and there are a lot of not very notable links of additional things you need to install. I think a Windows user could benefit from some additional instructions with pictures or a list of all the components which need to be installed, which included:
	○ Docker Desktop (Stable version) (https://hub.docker.com/editions/community/docker-ce-desktop-windows/)
	○ WSL 2 Linux kernel update (https://docs.microsoft.com/en-us/windows/wsl/install-win10)
	○ Ubuntu (https://docs.microsoft.com/en-us/windows/wsl/install-win10)
- In Docker Desktop, I also needed to go to Settings > Resources > WSL integration and click a toggle to enable integration with my freshly installed Ubuntu (picture below). This was not included in any of the installation instructions, so it would be good to include this in the lesson.
![Docker-resources](https://user-images.githubusercontent.com/12005921/93580537-9a7e1e80-f9a8-11ea-95bf-82e62ac31766.png)

**Installing**
- It was not for example clear for me based on the instructions, that I should also install Ubuntu. For Windows users, this link about WSL installation could be provided here in the intructions as well, as it is a bit hidden on Docker's own web page: https://docs.microsoft.com/en-us/windows/wsl/install-win10

**Testing**
- Not being very familiar with Docker, I did not first know where I should run the commands. It would be good to specify, that you should do that in Linux terminal (for example I initially run them in the command prompt in Windows).

### Using Docker with the CMS open data

**Install Docker**
- This section could be removed, as the same information is already covered on the previous page

**Using the proper image for CMS software**
- It was not evidently clear for me in the beginning that the different Bash boxes are part of the same command. I accidentally ran two first boxes of code doing a similar thing twice.
	○ Instead of using conditional here: "It might be worth breaking down this command for the interested user. ", one could write a bit more straight such as: "Below we break down the command for the interested user."
	○ Maybe explanatory Bash-boxes could even be of different color than the ones you are supposed to run? Or have different titles
- As I was running the commands from a freshly installed Ubuntu on my Windows computer, some parts of the first command were not needed as I for example did not have ssh keys ready. I think it would be best to give the user the simplest version of the command first, so that it will work for everyone.

**CHALLENGE! Test X11 forwarding**
- "Go into the Docker environment" was not clear enough instruction for me as I am not so familiar with using Docker, so it would have been helpful to have the exact command here.

**Overall comments on Using Docker with the CMS open data**
- When running the commands on this page, I also run into a problem that docker starts a background process, which consumes a huge amount of RAM even after the docker containers are not running anymore, and it sometimes made the computer so laggy that I needed to turn it off and on again. I found this instruction online, which could be useful for some people:  https://medium.com/@lewwybogus/how-to-stop-wsl2-from-hogging-all-your-ram-with-docker-d7846b9c5b37 
- As a Windows user who is not familiar with using the command line that much, I felt quite lost and uncertain of what I was supposed to do (and why some things did not work). For example I ran the first command on the page many time unsuccesfully, and even when I got an error message before the container was successfully created, Docker used quite a lot of storage space on my computer. After I realized to go to Docker desktop icon on "hidden icons" at the Windows toolbar > Troubleshoot > Clean / Purge data, 15 GB of much needed space was released on my C drive. This was very useful trick to free up space to be able to run the commands again succesfully.
- I have now used around 2.5 working days for a lesson which was instructed to take 1 hour 30 minutes (and still have not managed to run all the things succesfully). I did not manage to do some of the things right before Kati explained them to me with screen share, so I believe it would be really helpful for Windows users to give a bit more detailed instructions. I have tried to give concrete suggestions for this above.
- I had this issue, that whenever I run a container, it exits without doing anything. I had to fix it with these instructions: https://opendata-forum.cern.ch/t/running-cms-opendata-containers-in-wsl2/30
- As I was already running Linux on my Windows and had the above issue with the container, for me it was not clear where I should do things when talking about local machine (should I use the command prompt of Windows or Linux when I am not in the container)

----------------------

Above are my initial remarks I originally posted, here are some more when I tried to proceed:

**Checkout a git repository**
- I did not do this as I thought it is not necessary for the following exercise and was not familiar with the ssh keys

### Setting up CVMFS for use with the luminosity tools

**Installing CVMFS locally**
- When trying to install CVMFS and run cvmfs_config setup, I got the following message:
"noora@DESKTOP-9FMJT1Q:~$ cvmfs_config setup
cvmfs_config: command not found"

This is where I stopped as I didn't know how to go forward, and Kati promised to go through the exercise and see if she could get it working.

**Comment by mattbellis** [comment]
This is all great! I'll get on this today! It might take me until the weekend to get this all incorporated.

**Comment by caredg** [comment]
Hi @mattbellis.  Could you also please include [this validation](https://cms-opendata-workshop.github.io/workshop-lesson-virtualmachine/04-validation/#run-a-simple-demo-for-testing-and-validating) exercise as part of the docker exercises.  Basically you can copy it verbatim (you can remove the initial stuff specific for VMs).  I sort of need that both, the VM and the Docker setup, run the mkedanalyzr example because the CMSSW lesson relies heavily on that.  Thanks!

**Comment by mattbellis** [comment]
@Mmintyyy Thanks for these comments! My responses below...

* Changed to read "hard drive" for the memory comments. 

* Re: Windows, I believe that Kati has provided some guidance on what to include for this. 

* Removed the section about "Installing Docker" That was lingering from a different organization of the lesson. 

* I've now added a comment in the "Setup" about the user needing to be familiar with command-line interfaces and added a link to the SWC lesson on the Unix shell. 

   Not sure if we have everything necessary yet to help Windows users.

**Comment by mattbellis** [comment]
@caredg Done! I'm going through it now to remove the VM comments (and the references to emacs and nano...they don't exist in the docker image!). Also running the demo now!

**Comment by mattbellis** [comment]
@caredg The demo worked great in docker!
