### ISSUE TITLE
04 - correct the wording for trigger tools

### ISSUE THREAD

**Issue by katilp** [cms-opendata-workshop/workshop-lesson-docker-preexercises#4]
The trigger tools intended in https://cms-opendata-workshop.github.io/workshop-lesson-docker-preexercises/04-cvmfs-and-brilcalc/index.html are part of `brilcalc` (@caredg , right?).

Therefore:

At some point you may want to calculate the luminosity for the data you are analyzing. CMS uses a tool called brilcalc but it is not included in the Docker image. Similarly, there are some tools needed to calculate trigger effects/efficiencies that are also not included in the Docker image.

->

At some point you may want to calculate the luminosity or study trigger effects for the data you are analyzing. CMS uses a tool called brilcalc but it is not included in the Docker image.

**Comment by mattbellis** [comment]
Ok, I thought the trigger tools were different from brilcalc. My misunderstanding. 

Language is changed! Thanks!
