### ISSUE TITLE
04: cvmfs installation

### ISSUE THREAD

**Issue by katilp** [cms-opendata-workshop/workshop-lesson-docker-preexercises#5]
I had trouble understanding up to where I should follow the cvmfs installation instructions.
In addition to pointing to cvmfs instructions (https://cvmfs.readthedocs.io/en/stable/cpt-quickstart.html#), it would be useful to specify that one should do

https://cvmfs.readthedocs.io/en/stable/cpt-quickstart.html#getting-the-software
**and**
https://cvmfs.readthedocs.io/en/stable/cpt-quickstart.html#setting-up-the-software

**and** in
https://cvmfs.readthedocs.io/en/stable/cpt-quickstart.html#create-default-loc

one should tell what value to set, presumably (but I'm not sure, pls verify):
```
CVMFS_REPOSITORIES=cms.cern.ch,cms-opendata-conddb.cern.ch 
CVMFS_CLIENT_PROFILE=single
```

Specifically on WSL2 Ubuntu, after the installation, on each session, one has to:

```
sudo /usr/sbin/automount --pid-file /var/run/autofs.pid
cvmfs_config probe
```

Then I can open the docker container e.g. with

 docker run -it --name mycvmfs --volume "/cvmfs:/cvmfs:shared" cmsopendata/cmssw_5_3_32 /bin/bash

It is a bit confusing in the instructions to have just the arguments

> In the previous instructions on starting up your Docker container, the following arguments were used...

(also  because in the previous page the cvmfs installation was not yet done)

It would be better to give the full command.

**Comment by mattbellis** [comment]
On my machine, I had default.local contain

```
CVMFS_REPOSITORIES=cms-bril.cern.ch
CVMFS_HTTP_PROXY=DIRECT
CVMFS_CLIENT_PROFILE=single
```

But you have a couple of other repositories. I'll add them all for now as I don't think it will matter.

**Comment by katilp** [comment]
OK, thanks, I see.  This comes then once you have installed brilcalc on your machine (?).  I'm a bit uncertain on this as it is done in pre-exercise and used only later on. 
At least for me, when I open my linux again, I need to redo

```
sudo /usr/sbin/automount --pid-file /var/run/autofs.pid
cvmfs_config probe
```
to have the cvmfs in place. That, or anything similar to be done on other platforms, would need to be taken into account in the lumi exercise @tpmccauley

However, for the config files, I would not know what to do when reading this: "Pay particular attention to the setup procedure. You may have to create/edit some important config files."

**Comment by mattbellis** [comment]
Good point on the "Pay attention..." Removed. 

OK, these and some related changes are made and pushed!
