### ISSUE TITLE
03: using docker with cms

### ISSUE THREAD

**Issue by katilp** [cms-opendata-workshop/workshop-lesson-docker-preexercises#6]
Comments to https://cms-opendata-workshop.github.io/workshop-lesson-docker-preexercises/03-testing-docker-for-cms-opendata/index.html

- [x] For WSL2 users, point to https://opendata-forum.cern.ch/t/running-cms-opendata-containers-in-wsl2/30. The CMS OD containers will exit without giving the bash prompt on WSL2 if this fix is not done.

- [x] show the expected message and prompt when the OD container open properly i.e.

```
Setting up CMSSW_5_3_32                                                                                                                                                                      
CMSSW should now be available.                                                                                                                                                               
[21:53:43] cmsusr@docker-desktop ~/CMSSW_5_3_32/src $ 
```

- [ ] Is the ssh stuff really necessary in a pre-exercise? They are not in the mandatory pre-exercises,  it is not needed for the workshop material, and for those who do not use it or are new to all this, it just adds an additional hurdle
 
- [x] Simplify "The -it option means to start the instance in interactive mode and using a pseudo-TTY display." -> "The -it option means to start the instance in interactive mode."

- [x] Mention that X11-forwarding does not work when running docker from Windows10 WSL2 linux

- [x] Under "start docker by name" : the command is wrong, having done the earlier command first, I get an error with it, i.e.

```
kati@LAPTOP-xxx:~$ docker run -it --name MYOPENDATAPROJECT -v ${HOME}/.ssh:/home/cmsusr/.ssh --net=host --env="DISPLAY" --volume="$HOME/.Xauthority:/root/.Xauthority:rw" cmsopendata/cmssw_5_3_32 /bin/bash                                                                                                                                                                         
Setting up CMSSW_5_3_32                                                                                                                                                                      
CMSSW should now be available.                                                                                                                                                               
[21:54:01] cmsusr@docker-desktop ~/CMSSW_5_3_32/src $ exit                                                                                                                                   
exit                                                                                                                                                                                         
kati@LAPTOP-xxx:~$ docker start -i MYOPENDATAPROJECT --volume "/cvmfs:/cvmfs:shared"  -v ${HOME}/.ssh:/home/cmsusr/.ssh --net=host --env="DISPLAY" --volume="$HOME/.Xauthority:/root/.Xauthority:rw" /bin/bash                                                                                                                                                                       
unknown flag: --volume                                                                                                                                                                      See 'docker start --help'.  
```
I do not know if one can mount a volume to an existing container. The following works

`docker run -it --volume "/cvmfs:/cvmfs:shared" cmsopendata/cmssw_5_3_32 /bin/bash    
`

In any case, the cvmfs stuff is misplaced here as it only comes in the page that follows.

- [x] Simplify again "You will also use -i for interactive rather than -it for the pseudo-TTY display." -> "You will also use -i for interactive rather than -it ."

- [x] X11 challenge is a difficult one for WSL2 users. Mention that root GUI won't work. 
"
- [x] In X11 challenge: "Go into the Docker environment" -> "Open the CMS open data container with `docker start...` or `docker run...`  as instructed above"

- [x] Do not give the failing git command in the code box, but just in the text

**Comment by mattbellis** [comment]
I'm going through your comments here and will check them off as they're incorporated. Alternatively, if I have questions, I'll respond here. 

Re: ssh. Do you mean the section where I have them clone a repository? My thoughts are that if people go off and start working on their own analysis, they might be developing their code inside a container. At which point they'll want to be able to clone it and push their changes. Is there a different workflow we are imagining? I can remove it, but I thought it would be useful to users down the road, even if it's not immediately used in the workshop.

**Comment by mattbellis** [comment]
Re: "Under "start docker by name" : the command is wrong, having done the earlier command first, I get an error with it, i.e..."

Yeah, I found this tonight also. Fixed to reference the "docker start -i NAMEOFCONTAINER" approach. That will work and it will pick up all the volumes you mounted with the original command. At least, that's how it works on my machine. 

Let me know if the new instructions work for you!

**Comment by katilp** [comment]
For ssh, I'm thinking of people who are beginners and not familiar with git. Of course this is good to know, but we cannot possibly teach everything in this workshop and we should concentrate on the essential OD part as much as possible. It is very good to mention, but maybe not in the pre-exercises, because for beginners, it may be too much and they drop out thinking that they never get the environment to work with all the new things they have to learn.

**Comment by mattbellis** [comment]
Sounds good, re: ssh. Removing!

**Comment by mattbellis** [comment]
Remove the git section as well?

**Comment by katilp** [comment]
The section "Checkout a git repository" is very good and beginner-friendly, don't remove that.

**Comment by mattbellis** [comment]
k! So just remove the section on ssh keys?

**Comment by mattbellis** [comment]
I think I'm unsure of which sections you were referring to now regarding ssh being not necessary.

**Comment by katilp** [comment]
Right at the start, before the first command

It allows you to access ssh keys from inside the docker container. This means that if you are using ssh keys to connect to Github and have stored those keys locally, you will have an easier time cloning repositories.

**Comment by katilp** [comment]
NB: change: "If Docker is crashing on WSL2 (Windows), see this post in the CERN Open Data forum." -> "If the docker command exits without giving you this output on WSL2 (Windows), see this post in the CERN Open Data forum." **and** move it right after the output of the first docker command output at the start

Nothing crashes, and no error messages, it just exits and that is very confusing.

**Comment by mattbellis** [comment]
@katilp Text changed and moved for Windows information. 

I'm going to leave the comment about the ssh keys in there for now, but I added some text emphasis to show that this is only necessary if they need keys. We do have an optional pre-exercise about git if people want to learn more. 

Since we're suggesting that users include these command-line options, I feel it's worth explaining what that's for. I'm just concerned that people would ask what these flags are for. But maybe I'm the only one who would be *that* annoying student. :)

https://mattermost.web.cern.ch/it-dep/pl/5d69gt8rs3b6pbg71isfkgq7jo

**Comment by katilp** [comment]
OK, thanks. I was actually thinking removing them from the command as well, otherwise indeed removing them from the text does not make sense. But that's all fine 😃
