### ISSUE TITLE
About clipboard issue note in validation page

### ISSUE THREAD

**Issue by caredg** [cms-opendata-workshop/workshop-lesson-docker-preexercises#9]
@matt, [here](https://github.com/cms-opendata-workshop/workshop-lesson-docker-preexercises/blame/gh-pages/_episodes/05-validation.md#L63) I am not sure if this is possible with docker containers as it is with virtual machines.  Maybe this note should go?

**Comment by mattbellis** [comment]
OK, changed it so that it doesn't reference VMs. There are still sometimes issues so I mentioned trying Shift-Ctrl-V rather than Ctrl-V. It can't hurt to have it, even if there are no issues.
